[package]
name = "honeybee"
version = "0.1.0"

[dependencies]
actix = "0.5"
actix-web = "0.4"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
postgres = { version = "0.15", features = ["with-chrono"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
users = "0.4"
